export type Blog = {
    title: string;
    desc: string;
    image: string;
    category: string;
    author: string;
    authorRole: string;
    authorCompany: string;
    authorCompanyUrl: string;
    authorImage: string;
    slug: string;
};

export const BLOGS = [
    {
        title: "Voice AI in Healthcare: Revolutionizing Patient Care and Operational Efficiency",
        desc: "Discover how voice AI is transforming healthcare with real-time diagnostics, automated documentation, and 24/7 patient support. Learn how SaaS founders can tap into this $10B+ market opportunity while improving patient outcomes and reducing costs.",
        image: "/images/blog1.svg",
        category: "Voice AI in Healthcare",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-ai-healthcare",
    },
    {
        title: "Vapi vs Retell: The Ultimate Voice Agent Platform Comparison",
        desc: "An in-depth technical comparison of the leading voice agent platforms. Real performance data, code examples, and pricing analysis to help you choose the right solution for your SaaS.",
        image: "/images/blog2.svg",
        category: "Technology Comparison",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "vapi-vs-retell-comparison",
    },
    {
        title: "Building SaaS Startups with Voice Technology: The Next Frontier for Founders",
        desc: "From concept to scale: A founder's guide to integrating voice AI into your SaaS product. Learn proven strategies for implementation, avoiding common pitfalls, and positioning your startup for success in the voice-first revolution.",
        image: "/images/blog3.svg",
        category: "SaaS & Voice Tech",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "saas-voice-technology-guide",
    },
    {
        title: "The Future of Customer Service: How Voice Agents Are Replacing Traditional Support",
        desc: "Explore the ROI of voice-powered customer service and why 73% of consumers prefer talking to AI over waiting on hold. Get actionable insights on building customer service solutions that scale while improving satisfaction scores.",
        image: "/images/blog1.svg",
        category: "Customer Service",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-customer-service-future",
    },
    {
        title: "Voice Biometrics Security: Protecting Your SaaS with Next-Gen Authentication",
        desc: "Voice biometrics offer 99.8% accuracy in user identification. Learn how to implement enterprise-grade voice security in your SaaS platform, comply with regulations, and build unbreakable customer trust.",
        image: "/images/blog2.svg",
        category: "Security",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-biometrics-security",
    },
    {
        title: "Multi-Language Voice AI: Breaking Barriers for Global SaaS Expansion",
        desc: "Master the art of building voice AI that speaks your customers' language—literally. Discover how to scale your SaaS globally with voice technology that understands cultural nuances and maintains accuracy across 50+ languages.",
        image: "/images/blog3.svg",
        category: "Global Expansion",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "multilingual-voice-ai-expansion",
    },
    {
        title: "The ROI of Voice Agents: Why SaaS Founders Are Betting Big on Conversational AI",
        desc: "Crunch the numbers: See real case studies of SaaS companies achieving 300% ROI with voice agents. From reducing support costs to increasing conversion rates, understand the financial case for going voice-first in your startup.",
        image: "/images/blog1.svg",
        category: "ROI & Analytics",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-agents-roi-analysis",
    },
    {
        title: "Real-Time Voice Processing: Building Low-Latency Voice Agents for Modern SaaS",
        desc: "Deep dive into the technical architecture of sub-200ms voice agents. Learn about WebRTC, audio streaming, and edge computing strategies that power the world's most responsive voice interfaces.",
        image: "/images/blog2.svg",
        category: "Engineering",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "realtime-voice-processing",
    },
    {
        title: "Voice AI in E-commerce: Converting Shoppers with Conversational Commerce",
        desc: "How voice commerce is increasing conversion rates by 45% and reducing cart abandonment. Discover voice-first shopping experiences, voice-activated recommendations, and the future of retail.",
        image: "/images/blog3.svg",
        category: "E-commerce",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-ai-ecommerce",
    },
    {
        title: "Voice Agent Testing: Quality Assurance for Conversational AI",
        desc: "Comprehensive guide to testing voice agents - from unit testing conversation flows to load testing with thousands of concurrent users. Ensure your voice AI delivers consistent, reliable experiences.",
        image: "/images/blog1.svg",
        category: "Testing & QA",
        author: "Polar Voice Team",
        authorRole: "Voice AI Specialists",
        authorCompany: "Polar Voice",
        authorCompanyUrl: "https://polarvoice.ai",
        authorImage: "",
        slug: "voice-agent-testing-guide",
    },
];
