export const TESTIMONIALS = [
    {
        name: "Dr. Sarah Chen",
        role: "CEO & Founder",
        company: "HealthAI Diagnostics",
        companyUrl: "https://healthai-diagnostics.com",
        image: "/images/testimonials/person1.jpg",
        content: "Voice agents have revolutionized our patient triage system. We've reduced call center costs by 40% while improving response times from 15 minutes to under 2 minutes. The HIPAA-compliant AI handles complex medical inquiries with 95% accuracy, freeing our nurses for critical cases. This isn't just technology—it's better patient care at scale.",
        time: "9:30 AM",
        date: "Jun 20, 2024",
    },
    {
        name: "Marcus Rodriguez",
        role: "CTO",
        company: "FinSecure",
        companyUrl: "https://finsecure.tech",
        image: "/images/testimonials/person2.jpg",
        content: "In fintech, security and compliance are non-negotiable. Our voice agent handles 10,000+ daily customer interactions with zero security breaches, reducing fraud detection time from hours to seconds. We've cut operational costs by 60% while maintaining PCI-DSS compliance. Voice AI isn't the future of banking—it's the present.",
        time: "2:15 PM",
        date: "Jul 2, 2024",
    },
    {
        name: "Aisha Thompson",
        role: "Product Manager",
        company: "EduSmart",
        companyUrl: "https://edusmart.ai",
        image: "/images/testimonials/person3.jpg",
        content: "Our voice-powered tutoring system has increased student engagement by 75% and reduced support tickets by 80%. The AI adapts to learning styles in real-time, providing personalized education that feels human. We've seen a 40% improvement in course completion rates—this is transforming how we deliver accessible, effective education.",
        time: "11:45 AM",
        date: "Aug 15, 2024",
    },
    {
        name: "James Wilson",
        role: "Founder & CEO",
        company: "ShopFlow",
        companyUrl: "https://shopflow.com",
        image: "/images/testimonials/person4.jpg",
        content: "Voice commerce is the next frontier. Our AI-powered shopping assistant has increased conversion rates by 35% and average order value by 25%. Customers can browse, compare, and purchase hands-free with 92% satisfaction rates. We've reduced cart abandonment by half—voice isn't just convenient, it's profitable.",
        time: "4:20 PM",
        date: "Sep 5, 2024",
    },
    {
        name: "Dr. Lisa Park",
        role: "Medical Director",
        company: "MediCare Plus",
        companyUrl: "https://medicare-plus.com",
        image: "/images/testimonials/person1.jpg",
        content: "Our voice agent handles medication reminders, appointment scheduling, and symptom checking for 50,000+ patients. Readmission rates dropped 18% and patient satisfaction scores hit 4.8/5. The AI's medical knowledge base is constantly updated with latest protocols, ensuring patients always get current, accurate guidance.",
        time: "10:10 AM",
        date: "Oct 10, 2024",
    },
    {
        name: "Carlos Mendes",
        role: "Customer Experience Lead",
        company: "TravelEase",
        companyUrl: "https://travelease.com",
        image: "/images/testimonials/person2.jpg",
        content: "In travel, every second counts during booking season. Our multilingual voice agent handles 24/7 customer inquiries across 12 languages with 96% accuracy. We've reduced response times from 10 minutes to 15 seconds and increased international bookings by 45%. Global reach without the global support team overhead.",
        time: "3:30 PM",
        date: "Nov 25, 2024",
    },
];
